import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.7";

const CORS_HEADERS = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "POST, OPTIONS", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, accept, x-mcp-secret", "Content-Type": "application/json" };
const SERVER_INFO = { name: "tokenhealthscan-cms", version: "1.0.0" };
const SITE_URL = "https://tokenhealthscan.com";
const TOOLS = [
  { name: "list_pages", description: "List CMS pages by status, category, or search term.", inputSchema: { type: "object", properties: { status: { type: "string", enum: ["draft", "published", "all"] }, category: { type: "string" }, search: { type: "string" } } } },
  { name: "get_page", description: "Get a CMS page by id or slug with English content.", inputSchema: { type: "object", properties: { id: { type: "string" }, slug: { type: "string" } } } },
  { name: "upsert_page", description: "Create or update a CMS page and English translation.", inputSchema: { type: "object", properties: { id: { type: "string" }, slug: { type: "string" }, status: { type: "string", enum: ["draft", "published"] }, category: { type: "string" }, title: { type: "string" }, meta_description: { type: "string" }, content: { type: "string" }, featured_image: { type: "string" }, featured_image_alt: { type: "string" }, author_name: { type: "string" }, read_time: { type: "string" }, tags: { type: "array", items: { type: "string" } }, is_featured: { type: "boolean" }, schema: { type: "object" } }, required: ["slug", "title"] } },
  { name: "publish_page", description: "Publish a page and regenerate CMS outputs.", inputSchema: { type: "object", properties: { slug: { type: "string" }, id: { type: "string" } } } },
  { name: "unpublish_page", description: "Set a page to draft and refresh CMS outputs.", inputSchema: { type: "object", properties: { slug: { type: "string" }, id: { type: "string" } } } },
  { name: "delete_page", description: "Delete a non-system CMS page and refresh outputs.", inputSchema: { type: "object", properties: { slug: { type: "string" }, id: { type: "string" } } } },
  { name: "upload_image", description: "Upload a base64 image to blog-images/cms/covers.", inputSchema: { type: "object", properties: { filename: { type: "string" }, content_type: { type: "string" }, base64: { type: "string" } }, required: ["filename", "base64"] } },
  { name: "regenerate_outputs", description: "Regenerate RSS, llms.txt, and CMS snapshots.", inputSchema: { type: "object", properties: { slug: { type: "string" }, all: { type: "boolean" } } } },
];
function safeEqual(a: string, b: string) { if (a.length !== b.length) return false; let out = 0; for (let i = 0; i < a.length; i++) out |= a.charCodeAt(i) ^ b.charCodeAt(i); return out === 0; }
function slugify(s: string) { return s.toLowerCase().trim().replace(/['’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 120); }
function supabase() { return createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!); }
async function regenerate(slug?: string) { const base = Deno.env.get("SUPABASE_URL")!; const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!; await Promise.allSettled([fetch(`${base}/functions/v1/generate-cms-rss`, { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" } }), fetch(`${base}/functions/v1/generate-cms-llms-txt`, { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" } }), fetch(`${base}/functions/v1/regenerate-cms-snapshot`, { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify(slug ? { slug } : { all: true }) })]); }
function mapPage(row: any) { const t = Array.isArray(row.page_translations) ? row.page_translations[0] : row.page_translations; return { ...row, translation: t, url: `${SITE_URL}/publications/${t?.slug || row.slug}` }; }
async function listPages(args: any) { const db = supabase(); let q = db.from("pages").select("*, page_translations(*)").eq("page_translations.language", "en").order("updated_at", { ascending: false }).limit(50); if (args.status && args.status !== "all") q = q.eq("status", args.status); if (args.category) q = q.eq("category", args.category); const { data, error } = await q; if (error) throw error; let rows = (data || []).map(mapPage); if (args.search) rows = rows.filter((p: any) => JSON.stringify(p).toLowerCase().includes(args.search.toLowerCase())); return rows; }
async function getPage(args: any) { const db = supabase(); let q = db.from("pages").select("*, page_translations(*)").eq("page_translations.language", "en").limit(1); q = args.id ? q.eq("id", args.id) : q.eq("slug", args.slug); const { data, error } = await q.maybeSingle(); if (error) throw error; return data ? mapPage(data) : null; }
async function upsertPage(args: any) { const db = supabase(); const slug = slugify(args.slug || args.title); const payload = { slug, status: args.status || "draft", category: args.category || null, featured_image: args.featured_image || null, author_name: args.author_name || "Token Health Scan", read_time: args.read_time || null, tags: Array.isArray(args.tags) ? args.tags : [], is_featured: Boolean(args.is_featured) }; const { data: page, error } = args.id ? await db.from("pages").update(payload).eq("id", args.id).select("*").single() : await db.from("pages").upsert(payload, { onConflict: "slug" }).select("*").single(); if (error) throw error; const { error: tError } = await db.from("page_translations").upsert({ page_id: page.id, language: "en", title: args.title, meta_description: args.meta_description || null, content: args.content || null, featured_image_alt: args.featured_image_alt || null, slug, schema: args.schema || null }, { onConflict: "page_id,language" }); if (tError) throw tError; if (payload.status === "published") await regenerate(slug); return { ...page, url: `${SITE_URL}/publications/${slug}` }; }
async function setStatus(args: any, status: "draft" | "published") { const db = supabase(); const current = await getPage(args); if (!current) throw new Error("Page not found"); const { error } = await db.from("pages").update({ status }).eq("id", current.id); if (error) throw error; await regenerate(current.translation?.slug || current.slug); return { success: true, status, url: current.url }; }
async function deletePage(args: any) { const db = supabase(); const current = await getPage(args); if (!current) throw new Error("Page not found"); if (current.is_system_page) throw new Error("System pages cannot be deleted"); const slug = current.translation?.slug || current.slug; const { error } = await db.from("pages").delete().eq("id", current.id); if (error) throw error; await db.storage.from("seo-snapshots").remove([`publications/${slug}/index.html`]); await regenerate(); return { success: true, deleted: slug }; }
async function uploadImage(args: any) { const db = supabase(); const bytes = Uint8Array.from(atob(args.base64.replace(/^data:[^,]+,/, "")), (c) => c.charCodeAt(0)); const path = `cms/covers/${Date.now()}-${slugify(args.filename || "image")}`; const { error } = await db.storage.from("blog-images").upload(path, bytes, { contentType: args.content_type || "image/png", upsert: true }); if (error) throw error; return { path, publicUrl: db.storage.from("blog-images").getPublicUrl(path).data.publicUrl }; }
Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS_HEADERS });
  if (req.method !== "POST") return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405, headers: CORS_HEADERS });
  const secret = Deno.env.get("MCP_CONTENT_SECRET") || ""; const provided = req.headers.get("X-MCP-Secret") || "";
  if (!secret || !safeEqual(provided, secret)) return new Response(JSON.stringify({ jsonrpc: "2.0", error: { code: -32001, message: "Unauthorized" }, id: null }), { status: 401, headers: CORS_HEADERS });
  const raw = await req.text(); if (raw.length > 1_000_000) return new Response(JSON.stringify({ jsonrpc: "2.0", error: { code: -32000, message: "Request too large" }, id: null }), { status: 413, headers: CORS_HEADERS });
  let body: any; try { body = JSON.parse(raw); } catch { return new Response(JSON.stringify({ jsonrpc: "2.0", error: { code: -32700, message: "Parse error" }, id: null }), { status: 400, headers: CORS_HEADERS }); }
  const { method, params = {}, id } = body; const ok = (result: any) => new Response(JSON.stringify({ jsonrpc: "2.0", result, id }), { headers: CORS_HEADERS }); const err = (code: number, message: string) => new Response(JSON.stringify({ jsonrpc: "2.0", error: { code, message }, id }), { headers: CORS_HEADERS });
  try { if (method === "initialize") return ok({ protocolVersion: "2024-11-05", serverInfo: SERVER_INFO, capabilities: { tools: {} } }); if (method === "tools/list") return ok({ tools: TOOLS }); if (method === "tools/call") { const name = params.name; const args = params.arguments || {}; const handlers: Record<string, (a: any) => Promise<any>> = { list_pages: listPages, get_page: getPage, upsert_page: upsertPage, publish_page: (a) => setStatus(a, "published"), unpublish_page: (a) => setStatus(a, "draft"), delete_page: deletePage, upload_image: uploadImage, regenerate_outputs: async (a) => { await regenerate(a.slug); return { success: true }; } }; if (!handlers[name]) return err(-32601, `Unknown tool: ${name}`); const result = await handlers[name](args); return ok({ content: [{ type: "text", text: JSON.stringify(result, null, 2) }] }); } return err(-32601, "Method not found"); } catch (error) { return err(-32000, String(error?.message || error)); }
});
