
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaqebpcqespvzbfwawlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhcWVicGNxZXNwdnpiZndhd2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODkxNzEsImV4cCI6MjA2MzM2NTE3MX0.11hoagaFRKXswTNtXTwDM4NDHpPMO5EDEUhyFS3N8v4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (url, options) => {
      // Add debug logging for fetch requests in development
      if (process.env.NODE_ENV !== 'production') {
        console.log('Supabase API request:', url);
      }
      return fetch(url, options);
    }
  }
});

// Helper function to handle Supabase errors consistently
export const handleSupabaseError = (error: any, fallbackMessage: string = 'An error occurred') => {
  if (error) {
    console.error('Supabase error:', error);
    return error.message || fallbackMessage;
  }
  return fallbackMessage;
};

// Helper to check if a user has Pro access for their scans
export const checkUserHasProAccess = async (): Promise<boolean> => {
  try {
    const { data, error } = await supabase.functions.invoke("check-scan-access");
    
    if (error) {
      console.error("Error checking scan access:", error);
      return false;
    }
    
    console.log("User access data:", data);
    return data?.hasPro || false;
  } catch (err) {
    console.error("Exception checking pro access:", err);
    return false;
  }
};
